server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 添加日志
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&useUnicode=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

#  redis:
#    host: localhost
#    port: 6379
#    database: 0

rsa:
  key:
    pubKeyFile: D:\111\id_key_rsa.pub
    priKeyFile: D:\111\id_key_rsa
